# Generated by Django 2.1 on 2018-08-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_auto_20180819_0128'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX request_combined_index ON mainapp_request (district, requestee, requestee_phone, location)"),
        migrations.RunSQL("CREATE INDEX request_requestee_index ON mainapp_request (requestee, location)"),
        migrations.RunSQL("CREATE INDEX request_requestee_phone_index ON mainapp_request (requestee_phone, location)"),
        migrations.RunSQL("CREATE INDEX request_location_index ON mainapp_request (location)"),
        migrations.RunSQL("CREATE INDEX rescuecamp_district_index ON mainapp_rescuecamp (district)"),
        migrations.RunSQL("CREATE INDEX person_combined_index ON mainapp_person (name, phone, district)"),
        migrations.RunSQL("CREATE INDEX person_phone_gender_district ON mainapp_person (phone, district)"),
        migrations.RunSQL("CREATE INDEX person_gender_district_index ON mainapp_person (gender, district)"),
        migrations.RunSQL("CREATE INDEX person_district_index ON mainapp_person (district)"),
    ]
